version: '3.9'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - ./frontend:/app
            - node_modules:/app/node_modules
        command: npm run start
